echo BASE_URI_STRAPI=$BASE_URI_STRAPI >> .env
echo BASE_URL_PAGE=$BASE_URL_PAGE >> .env
echo COUNTRY_API_TOKEN=$COUNTRY_API_TOKEN >> .env
echo NETLIFY_AUTH_TOKEN=$NETLIFY_AUTH_TOKEN >> .env
echo NETLIFY_SITE_ID=$NETLIFY_SITE_ID >> .env
echo NX_PROJECT_ENV=$NX_PROJECT_ENV >> .env
echo SALESFORCE_CLIENT_ID=$SALESFORCE_CLIENT_ID >> .env
echo SALESFORCE_CLIENT_SECRET=$SALESFORCE_CLIENT_SECRET >> .env
echo SALESFORCE_GRANT_TYPE=$SALESFORCE_GRANT_TYPE >> .env
echo SALESFORCE_PASSWORD=$SALESFORCE_PASSWORD >> .env
echo SALESFORCE_USER=$SALESFORCE_USER >> .env
echo SALESFORCE_USER_URL=$SALESFORCE_USER_URL >> .env


